### ISSUE TITLE
upgrade to v3 weather API

### ISSUE THREAD

**Issue by JulianNorton** [JulianNorton/weather-milliseconds#1]
Right now this is using a legacy version of weather.gov.

~https://forecast-v3.weather.gov/documentation~ is the new API that will be supported moving forward.
https://api.weather.gov

**Comment by suvansh-rana** [comment]
Can you provide the exact URL of the endpoint of the new API?

The documentation link is not working.

**Comment by JulianNorton** [comment]
Thanks for letting me know @suvansh-rana , I am confirming https://forecast-v3.weather.gov/ is not working for me either!

I think they've moved it to production here: 
- https://www.weather.gov/documentation/services-web-api
- https://api.weather.gov/
- https://api.weather.gov/points/39.7456,-97.0892

**Comment by suvansh-rana** [comment]
I think for applying the use of new API in the project, we have to change the code too(not just the URL) because the JSON keys also appear to be changed in the new version.

Shall I do the code changes in my PR too?

**Comment by JulianNorton** [comment]
Please do!
Julian

**Comment by suvansh-rana** [comment]
Working on it.

**Comment by suvansh-rana** [comment]
Here you go #12

**Comment by JulianNorton** [comment]
Completed by @suvansh-rana !
