### ISSUE TITLE
Display the source (weather station or location) that the data is returning for

### ISSUE THREAD

**Issue by JulianNorton** [JulianNorton/weather-milliseconds#13]
![image](https://user-images.githubusercontent.com/2412992/66886962-481dcc00-efa7-11e9-80e1-bbe4f4663bab.png)

Right now, it just says "weather" in the H1. The solution to this ticket should so some indication as to where the source of the data is for. For example, if it's for "new york, ny" it should say that, or KNYC weather station, so that the data can be trusted and validated.

Current header:
https://github.com/JulianNorton/weather-milliseconds/blob/master/templates/index.html#L8

Current weather data source:
https://github.com/JulianNorton/weather-milliseconds/blob/master/app.py#L37

**Comment by sebasblancogonz** [comment]
I'll take this one!

**Comment by sebasblancogonz** [comment]
I've submitted a PR, let me know if it fits!

**Comment by JulianNorton** [comment]
Closed by https://github.com/JulianNorton/weather-milliseconds/pull/14
