### ISSUE TITLE
refactor css

### ISSUE THREAD

**Issue by JulianNorton** [JulianNorton/weather-milliseconds#4]
right now the css is targeting html selectors with inline css. PR should refactor css to:

1. Remove inline styles
2. Remove targeting of html elements directly (use a class instead of direct selector)
3. Move css to single stylesheet or inline

https://github.com/JulianNorton/weather-milliseconds/blob/master/templates/base.html

**Comment by jiwendi** [comment]
I will like to work on this.

**Comment by JulianNorton** [comment]
hey @alexmndzdev I appreciate the help. Can you help me understand what issue you're running into? You should be able to make a pull-request.

**Comment by harshini1** [comment]
@JulianNorton  Please review https://github.com/JulianNorton/weather-milliseconds/pull/7
